// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// NextAuth.js — API route handler.
// Place this at apps/web/src/pages/api/auth/[...nextauth].tsx
// TODO (hackathon): no changes needed here — NextAuth handles everything automatically.
import NextAuth from 'next-auth';
import { authOptions } from '../../auth';

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
