// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// NextAuth.js — Next.js middleware for route protection.
// Place this in apps/web/src/middleware.ts and it will run on every request.
// TODO (hackathon): update the protected routes to match your app's routing structure.
import { withAuth } from 'next-auth/middleware';
export default withAuth({
  // TODO (hackathon): set the login page URL
  // pages: { signIn: '/auth/signin' },
});

export const config = {
  // TODO (hackathon): update these to protect your routes
  matcher: [
    '/((?!api/auth|_next/static|_next/image|favicon.ico).*)',
  ],
};
