// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// NextAuth.js — adds OAuth sign-in (Google, GitHub) on top of Supabase Auth.
// Configure NEXTAUTH_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET in .env.local
// TODO (hackathon): customize the providers, callbacks, and session strategy.

import NextAuth, { type NextAuthOptions } from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
// import { supabaseAdapter } from 'next-auth-supabase-adapter'; // Optional: use Supabase as the NextAuth DB adapter

export const authOptions: NextAuthOptions = {
  // TODO (hackathon): add your providers here
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID ?? '',
      clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? '',
    }),
    // Add more OAuth providers: GitHub, Apple, etc.
  ],

  // TODO (hackathon): configure callbacks
  callbacks: {
    // session: ({ session, user }) => {
    //   return { ...session, user: { ...session.user, id: user.id } };
    // },
  },

  // TODO (hackathon): set pages
  pages: {
    // signIn: '/auth/signin',
    // error: '/auth/error',
  },

  // TODO (hackathon): use a database adapter if you want to persist sessions
  // adapter: supabaseAdapter,
};

export default NextAuth(authOptions);
