// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Stripe — API route for creating payment intents.
// Place at apps/web/src/pages/api/payments/create-payment-intent.ts
// TODO (hackathon): implement payment intent creation (requires authentication).
// import { NextResponse } from 'next/server';
// import { createPaymentIntent } from '@/lib/payments';

// export async function POST(req: Request) {
//   const { amount, currency = 'usd' } = await req.json();
//   const intent = await createPaymentIntent(amount, currency);
//   return NextResponse.json({ clientSecret: intent.client_secret });
// }
