// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Stripe payments — server-side payment intent creation.
// TODO (hackathon): customize the createPaymentIntent andWebhook functions.
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY ?? '', {
  apiVersion: '2024-11-20.acacia',
});

export const stripeClient = stripe;

// TODO (hackathon): implement payment helpers here
// export async function createPaymentIntent(amount: number, currency: string = 'usd') {
//   return stripe.paymentIntents.create({
//     amount: Math.round(amount * 100), // Stripe expects cents
//     currency,
//   });
// }

// TODO (hackathon): Stripe webhook handler
// export async function handleStripeWebhook(rawBody: string, signature: string) {
//   return stripe.webhooks.constructEvent(rawBody, signature, process.env.STRIPE_WEBHOOK_SECRET!);
// }
