// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// This file contains only the Supabase client setup.
// Add your database operations here ONLY AFTER the hackathon event has started.
import { createClient, SupabaseClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';

export const supabase: SupabaseClient = createClient(supabaseUrl, supabaseAnonKey);

// TODO (hackathon): add your database operations here
// Example:
// export async function getProjects() { ... }