// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// No auth provider selected — this app has no authentication.
// The app is fully public. If you need auth later, add it at the hackathon.
// TODO (hackathon): delete this file and add your auth provider if needed.

// Stub so other files that import from here don't break
export const authEnabled = false;
export const getCurrentUser = async () => null;
