// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// No payments — this app has no payment integration.
// TODO (hackathon): delete this file and add Stripe if you need payments.
export const paymentsEnabled = false;

export async function createPaymentIntent(amount: number, currency: string = 'usd') {
  throw new Error('Payments not enabled — add Stripe at the hackathon');
}
