// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// verda-gpu mode: inference is served directly on the rented Verda GPU machine.
// There is no Cloud Run inference service — instead:
//   - Next.js calls the Verda GPU machine directly via HTTP (public IP)
//   - provision.sh bootstraps the GPU machine at boot time
//   - deploy-to-verda.sh deploys updated images via SSH
//
// This file is a placeholder — verda-gpu does NOT use services/inference/ for serving.
// The frontend calls the Verda GPU machine directly at:
//   http://{{cookiecutter.verda_ssh_host}}:{{cookiecutter.verda_ssh_port}}
//
// TODO (hackathon): implement frontend inference calls here or in apps/web/src/lib/verda.ts
export {};
