// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Supabase Auth — the existing default. Supabase handles email/password, magic links, OTP.
// The supabase client in ../lib/supabase.ts is already configured.
// TODO (hackathon): use supabase.auth.signIn(), supabase.auth.signOut(), etc.
import { supabase } from '../lib/supabase';
export { supabase };

// TODO (hackathon): add your auth helpers here, e.g.:
// export async function signIn(email: string, password: string) {
//   return supabase.auth.signInWithPassword({ email, password });
// }
// export async function signUp(email: string, password: string) {
//   return supabase.auth.signUp({ email, password });
// }
// export async function signOut() {
//   return supabase.auth.signOut();
// }
// export async function getSession() {
//   return supabase.auth.getSession();
// }
