// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Supabase Auth — Next.js middleware for route protection.
// Place this in apps/web/src/middleware.ts and it will run on every request.
// TODO (hackathon): update the `protectedRoutes` and `redirectTo` paths as needed.
import { createServerClient, type CookieOptions, supabaseUrl, supabaseAnonKey } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

export async function middleware(request: NextRequest) {
  // TODO (hackathon): add your auth logic here
  // Example: protect all routes except /auth/*
  // const { data: { session } } = await supabase.auth.getSession();
  // if (!session && !request.nextUrl.pathname.startsWith('/auth')) {
  //   return NextResponse.redirect(new URL('/auth/login', request.url));
  // }
  return NextResponse.next();
}

export const config = {
  matcher: [
    // Skip static files and _next internals
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
