// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Inference service running on Cloud Run (serverless, auto-scales).
// Your Docker container is deployed to Google Cloud Run.
// Actual inference logic (calling models, handling streams) goes here ONLY AFTER the hackathon starts.

import express, { Request, Response } from 'express';

const app = express();
const PORT = parseInt(process.env.PORT ?? '3000', 10);

app.use(express.json());

// Health check
app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', service: 'inference-skeleton' });
});

// Inference endpoint — implement during hackathon
app.post('/api/inference', async (req: Request, res: Response) => {
  // TODO (hackathon): implement your inference logic here
  // - Call your model (local or external API)
  // - Handle streaming if needed
  // - Apply any preprocessing/postprocessing
  res.status(501).json({
    error: 'Not implemented',
    message: 'Write your inference logic here at the hackathon',
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Inference skeleton running on port ${PORT}`);
});
