// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Vercel serverless function skeleton.
// Write your API handlers HERE at the hackathon event.

import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // TODO (hackathon): implement your API logic here
  res.status(501).json({
    error: 'Not implemented',
    message: 'Write your API handler here at the hackathon',
  });
}