// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// React + Vite frontend scaffold.
// Write your frontend code HERE at the hackathon event.

import React from 'react';
import ReactDOM from 'react-dom/client';

function App() {
  return (
    <main>
      <h1>{{cookiecutter.project_name}}</h1>
      <p>Start coding here!</p>
      {/* TODO (hackathon): build your UI here */}
    </main>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);