# GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
# Queue worker scaffold (Python).
# Implements the queue_worker pattern with Upstash Redis.
# Write your worker logic HERE at the hackathon event.

import os
import asyncio
from typing import Any

import httpx
from upstash_redis import Redis

# ─── Upstash Redis client ───────────────────────────────────────────
redis_url = os.environ.get("UPSTASH_REDIS_REST_URL", "")
redis_token = os.environ.get("UPSTASH_REDIS_REST_TOKEN", "")

redis = Redis(url=redis_url, token=redis_token) if redis_url and redis_token else None

# ─── Inference endpoint ─────────────────────────────────────────────
# When backend_lang=python (FastAPI), inference runs as a separate Cloud Run service.
# The worker calls it directly via HTTP.
INFERENCE_API_URL = os.environ.get("INFERENCE_API_URL", "http://localhost:8080")


# ─── Worker loop ────────────────────────────────────────────────────
async def process_job(job: dict[str, Any]) -> dict[str, Any]:
    """
    Process a single queued job.
    TODO (hackathon): implement your inference logic here.
    """
    job_id = job.get("id", "?")
    payload = job.get("payload", {})

    print(f"[worker] Processing job {job_id}: {payload}")

    # TODO (hackathon): call your inference endpoint
    # async with httpx.AsyncClient(timeout=60.0) as client:
    #     response = await client.post(
    #         f"{INFERENCE_API_URL}/api/inference",
    #         json=payload,
    #     )
    #     response.raise_for_status()
    #     result = response.json()

    # TODO (hackathon): store result back to Redis if needed
    # await redis.set(f"result:{job_id}", json.dumps(result))

    return {"job_id": job_id, "status": "done"}


async def worker_loop(queue_name: str = "inference-queue") -> None:
    """
    Polls Upstash Redis for new jobs and processes them.
    TODO (hackathon): customise the polling interval, concurrency, error handling.
    """
    if redis is None:
        raise RuntimeError(
            "UPSTASH_REDIS_REST_URL / UPSTASH_REDIS_REST_TOKEN not set. "
            "Worker cannot connect to Redis."
        )

    print(f"[worker] Listening on queue: {queue_name}")
    print(f"[worker] Inference endpoint: {INFERENCE_API_URL}")

    while True:
        try:
            # BRPOP — blocking right-pop; waits up to 5s for a new item
            job_data = redis.rpop(queue_name)
            if job_data is None:
                await asyncio.sleep(1)
                continue

            import json

            job = json.loads(job_data) if isinstance(job_data, str) else job_data
            result = await process_job(job)
            print(f"[worker] Job done: {result}")

        except Exception as exc:
            print(f"[worker] Error processing job: {exc}")
            await asyncio.sleep(5)


if __name__ == "__main__":
    print("[worker] Starting Python queue worker...")
    asyncio.run(worker_loop())
