// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// This file is intentionally empty. Add your shared Zod schemas here
// ONLY AFTER the hackathon event has started.
export type HackathonType = never;