# GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
# FastAPI backend scaffold (Python).
# Write your API handlers HERE at the hackathon event.

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="{{cookiecutter.project_name}} API")

# CORS — allow frontend to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://*.vercel.app"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "ok", "service": "api-skeleton"}


@app.post("/api/")
async def api_root():
    # TODO (hackathon): implement your API logic here
    return {
        "error": "Not implemented",
        "message": "Write your API handler here at the hackathon",
    }


# TODO (hackathon): add your endpoints here
# Example:
# @app.post("/api/items/")
# async def create_item(item: ItemCreate):
#     return {"id": 1, "name": item.name}
#
# from pydantic import BaseModel
# class ItemCreate(BaseModel):
#     name: str
