// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// This file contains the Upstash Redis client setup for job queues and caching.
// Queue operations go here ONLY AFTER the hackathon event has started.

import { Redis } from '@upstash/redis';

const redisUrl = process.env.UPSTASH_REDIS_REST_URL ?? '';
const redisToken = process.env.UPSTASH_REDIS_REST_TOKEN ?? '';

export const redis = new Redis({
  url: redisUrl,
  token: redisToken,
});

// =============================================================================
// Queue helpers — implement your job queue logic here at the hackathon
// =============================================================================
// Example:
// export async function enqueueJob(queue: string, data: unknown) { ... }
// export async function dequeueJob(queue: string) { ... }

// TODO (hackathon): add your queue operations here
// - enqueue / dequeue for background jobs
// - cache helpers (get/set with TTL)
// - rate limiting helpers