-- GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
-- Run this migration in Supabase dashboard or via: npx supabase db push
-- Add your tables, RLS policies, and triggers HERE at the hackathon event.

-- Enable UUID extension (standard for Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- TODO (hackathon): add your tables here. Example:
-- CREATE TABLE public.my_table (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   name TEXT NOT NULL,
--   created_at TIMESTAMPTZ DEFAULT NOW()
-- );

-- Enable RLS on all tables (Supabase best practice)
-- TODO (hackathon): add your RLS policies after creating tables. Example:
-- ALTER TABLE public.my_table ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Users can read their own data" ON public.my_table
--   FOR SELECT USING (auth.uid() = user_id);

-- Auto-create profile on signup (standard Supabase pattern)
-- Uncomment and run this AFTER the profiles table is created at the hackathon:
-- CREATE OR REPLACE FUNCTION public.handle_new_user()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   INSERT INTO public.profiles (id, email)
--   VALUES (new.id, new.email);
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql SECURITY DEFINER;
-- CREATE TRIGGER on_auth_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();