// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Write your frontend code HERE at the hackathon event.

export default function Home() {
  return (
    <main>
      <h1>{{cookiecutter.project_name}}</h1>
      <p>Start coding here!</p>
      {/* TODO (hackathon): build your UI here */}
    </main>
  );
}