// GENERATED by cookiecutter — INFRASTRUCTURE ONLY, not feature code.
// Verda is a GPU rental service. You rent a bare GPU machine via SSH.
// Your startup script provisions the inference stack on that machine.
// TODO (hackathon): implement inference calls here — e.g. SSH to Verda machine and run inference
const VERDA_SSH_HOST = process.env.VERDA_SSH_HOST ?? '';
const VERDA_SSH_USER = process.env.VERDA_SSH_USER ?? '';
const VERDA_SSH_KEY_PATH = process.env.VERDA_SSH_KEY_PATH ?? '~/.ssh/id_ed25519';

export async function runInference(request: unknown): Promise<unknown> {
  // TODO (hackathon): connect via SSH to the Verda GPU machine and run inference
  // Example approach:
  //   1. Use `ssh2` library to connect to VERDA_SSH_HOST
  //   2. Execute inference command on remote machine
  //   3. Return result over SSH
  throw new Error('Not implemented — write your hackathon inference logic here');
}